INSERT INTO public."Categories"(
    "Id", "PersianName", "EnglishName", "ParentCategoryId", "ImageUrl", 
    "CategoryPersianDesc", "CategoryEnglishDesc", "IsShowInLanding", 
    "CreatedAt", "UpdatedAt", "DeletedAt", "IsDeleted", "IsActive", 
    "CreatedBy", "UpdatedBy", "DeletedBy"
) VALUES 
(
    1,
    'لوازم خانگی',
    'Home Appliances',
    NULL,
    '/uploads/categories/home-appliances.jpg',
    'دسته‌بندی نمونه برای لوازم خانگی و تجهیزات کاربردی منزل.',
    'Sample category for home appliances and everyday household equipment.',
    true,
    '2026-01-10 08:00:00',
    '2026-01-10 08:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    2,
    'دکوری و تزئینی',
    'Home Decor',
    NULL,
    '/uploads/categories/home-decor.jpg',
    'مجموعه‌ای از اقلام دکوری برای چیدمان فضای خانه و محل کار.',
    'A collection of decorative items for home and workspace styling.',
    true,
    '2026-01-10 08:05:00',
    '2026-01-10 08:05:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    3,
    'ظروف پذیرایی',
    'Serving Ware',
    NULL,
    '/uploads/categories/serving-ware.jpg',
    'ظروف و ست‌های پذیرایی مناسب مهمانی و استفاده روزمره.',
    'Serving sets and tableware suitable for gatherings and daily use.',
    true,
    '2026-01-10 08:10:00',
    '2026-01-10 08:10:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    4,
    'آشپزخانه',
    'Kitchen',
    1,
    '/uploads/categories/kitchen.jpg',
    'ابزار و لوازم کاربردی آشپزخانه برای آماده‌سازی و پخت غذا.',
    'Practical kitchen tools for food preparation and cooking.',
    false,
    '2026-01-12 09:00:00',
    '2026-01-12 09:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    5,
    'گلدان و گل‌آرایی',
    'Vases & Florals',
    2,
    '/uploads/categories/vases.jpg',
    'گلدان‌ها و اقلام تزئینی مرتبط با گل‌آرایی فضای داخلی.',
    'Vases and decorative pieces for indoor floral arrangements.',
    false,
    '2026-01-12 09:15:00',
    '2026-01-12 09:15:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    6,
    'ست میز',
    'Table Sets',
    3,
    '/uploads/categories/table-sets.jpg',
    'ست‌های هماهنگ برای چیدمان میز پذیرایی.',
    'Coordinated sets for table presentation.',
    false,
    '2026-01-15 10:00:00',
    '2026-01-15 10:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    7,
    'ابزار پخت',
    'Cookware',
    4,
    '/uploads/categories/cookware.jpg',
    'قابلمه، تابه و ابزارهای مرتبط با پخت‌وپز.',
    'Pots, pans and related cookware items.',
    false,
    '2026-01-15 10:30:00',
    '2026-01-15 10:30:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    8,
    'هدایا',
    'Gifts',
    NULL,
    '/uploads/categories/gifts.jpg',
    'پیشنهادهای هدیه برای مناسبت‌های مختلف.',
    'Gift ideas for different occasions.',
    true,
    '2026-01-18 11:00:00',
    '2026-01-18 11:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    9,
    'سازماندهی منزل',
    'Home Organization',
    NULL,
    '/uploads/categories/organization.jpg',
    'باکس، قفسه و اقلام نظم‌دهی فضای خانه.',
    'Boxes, shelves and organizers for tidy living spaces.',
    false,
    '2026-01-20 13:30:00',
    '2026-01-20 13:30:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    10,
    'روشنایی دکوری',
    'Decorative Lighting',
    2,
    '/uploads/categories/lighting.jpg',
    'چراغ و آباژورهای تزئینی برای فضای داخلی.',
    'Decorative lamps and lighting for interior spaces.',
    true,
    '2026-01-22 15:45:00',
    '2026-01-22 15:45:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
);
