INSERT INTO public."Categories"(
    "Id", "PersianName", "EnglishName", "ParentCategoryId", "ImageUrl", 
    "CategoryPersianDesc", "CategoryEnglishDesc", "IsShowInLanding", 
    "CreatedAt", "UpdatedAt", "DeletedAt", "IsDeleted", "IsActive", 
    "CreatedBy", "UpdatedBy", "DeletedBy"
) VALUES 
(
    1,
    'عطرهای زنانه',
    'Women Perfumes',
    NULL,
    '/uploads/categories/women-perfumes.jpg',
    'مجموعه‌ای از بهترین و پرطرفدارترین عطرهای زنانه با رایحه‌های گلی، میوه‌ای، شیرین و چوبی. مناسب برای سلیقه‌های مختلف و موقعیت‌های گوناگون.',
    'A collection of the best and most popular women''s perfumes with floral, fruity, sweet and woody scents. Suitable for different tastes and various occasions.',
    true,
    '2026-01-10 08:00:00',
    '2026-01-10 08:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    2,
    'عطرهای مردانه',
    'Men Perfumes',
    NULL,
    '/uploads/categories/men-perfumes.jpg',
    'مجموعه‌ای از بهترین عطرهای مردانه با رایحه‌های چوبی، ادویه‌ای، چرمی و خنک. مناسب برای آقایان با سلیقه‌های متفاوت از کلاسیک تا مدرن.',
    'A collection of the best men''s perfumes with woody, spicy, leathery and fresh scents. Suitable for men with different tastes from classic to modern.',
    true,
    '2026-01-10 08:05:00',
    '2026-01-10 08:05:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    3,
    'عطرهای یونیسکس',
    'Unisex Perfumes',
    NULL,
    '/uploads/categories/unisex-perfumes.jpg',
    'عطرهای مناسب برای هر دو جنسیت با رایحه‌های متعادل و همه‌پسند. انتخاب ایده‌آل برای افرادی که به دنبال عطرهای خاص و منحصر به فرد هستند.',
    'Fragrances suitable for both genders with balanced and crowd-pleasing scents. Ideal choice for those looking for special and unique perfumes.',
    true,
    '2026-01-10 08:10:00',
    '2026-01-10 08:10:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    4,
    'عطرهای گلی',
    'Floral Perfumes',
    1,
    '/uploads/categories/floral-perfumes.jpg',
    'عطرهای با رایحه‌های گلی مانند رز، یاسمن، گل مریم و زنبق. این دسته از عطرها حس طراوت و لطافت را منتقل می‌کنند و بسیار محبوب هستند.',
    'Fragrances with floral scents such as rose, jasmine, tuberose and iris. These perfumes convey a sense of freshness and delicacy and are very popular.',
    false,
    '2026-01-12 09:00:00',
    '2026-01-12 09:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    5,
    'عطرهای میوه‌ای',
    'Fruity Perfumes',
    1,
    '/uploads/categories/fruity-perfumes.jpg',
    'عطرهایی با رایحه‌های میوه‌ای مانند سیب، گلابی، توت‌فرنگی و مرکبات. این عطرها انرژی‌بخش و شاداب هستند و معمولاً در فصل‌های گرم سال طرفداران زیادی دارند.',
    'Fragrances with fruity scents such as apple, pear, strawberry and citrus. These perfumes are energizing and refreshing and usually have many fans in warm seasons.',
    false,
    '2026-01-12 09:15:00',
    '2026-01-12 09:15:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    6,
    'عطرهای چوبی',
    'Woody Perfumes',
    2,
    '/uploads/categories/woody-perfumes.jpg',
    'عطرهایی با رایحه‌های چوبی مانند چوب صندل، سدر، عود و پاتچولی. این عطرها گرم و ماندگار هستند و معمولاً برای فصول سرد سال و محیط‌های رسمی انتخاب می‌شوند.',
    'Fragrances with woody scents such as sandalwood, cedar, agarwood and patchouli. These perfumes are warm and long-lasting and are usually chosen for cold seasons and formal environments.',
    false,
    '2026-01-15 10:00:00',
    '2026-01-15 10:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    7,
    'عطرهای ادویه‌ای',
    'Spicy Perfumes',
    2,
    '/uploads/categories/spicy-perfumes.jpg',
    'عطرهایی با رایحه‌های ادویه‌ای مانند دارچین، زعفران، فلفل و میخک. این عطرها گرم، تند و جذاب هستند و شخصیت خاصی به کاربر خود می‌دهند.',
    'Fragrances with spicy scents such as cinnamon, saffron, pepper and clove. These perfumes are warm, sharp and attractive and give a special character to the user.',
    false,
    '2026-01-15 10:30:00',
    '2026-01-15 10:30:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    8,
    'عطرهای شرقی',
    'Oriental Perfumes',
    NULL,
    '/uploads/categories/oriental-perfumes.jpg',
    'عطرهایی با رایحه‌های گرم، شیرین و غلیظ مانند عنبر، وانیل، مشک و کهربا. این عطرها بسیار ماندگار هستند و حس لوکس و مجلل را منتقل می‌کنند.',
    'Fragrances with warm, sweet and intense scents such as ambergris, vanilla, musk and amber. These perfumes are very long-lasting and convey a sense of luxury and opulence.',
    true,
    '2026-01-18 11:00:00',
    '2026-01-18 11:00:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    9,
    'عطرهای مرکباتی',
    'Citrus Perfumes',
    NULL,
    '/uploads/categories/citrus-perfumes.jpg',
    'عطرهایی با رایحه‌های مرکباتی مانند لیمو، پرتقال، گریپ‌فروت و ترنج. این عطرها سبک، خنک و انرژی‌بخش هستند و برای استفاده روزانه در فصول گرم ایده‌آل می‌باشند.',
    'Fragrances with citrus scents such as lemon, orange, grapefruit and bergamot. These perfumes are light, cool and energizing and are ideal for daily use in warm seasons.',
    false,
    '2026-01-20 13:30:00',
    '2026-01-20 13:30:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    10,
    'عطرهای آبی',
    'Aquatic Perfumes',
    NULL,
    '/uploads/categories/aquatic-perfumes.jpg',
    'عطرهایی با رایحه‌های آبی، دریایی و اقیانوسی که حس تازگی و پاکی را تداعی می‌کنند. این عطرها بسیار محبوب هستند و برای استفاده روزانه و تابستان گزینه‌های عالی به شمار می‌روند.',
    'Fragrances with aquatic, marine and oceanic scents that evoke a sense of freshness and purity. These perfumes are very popular and are excellent choices for daily use and summer.',
    true,
    '2026-01-22 15:45:00',
    '2026-01-22 15:45:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
);