INSERT INTO public."Blogs"(
    "Id", "TitleFa", "IntroFa", "ContentFa", "ConclusionFa", "ExcerptFa", 
    "TitleEn", "IntroEn", "ContentEn", "ConclusionEn", "ExcerptEn", 
    "MetaDescriptionFa", "MetaDescriptionEn", "MetaKeywordsFa", "MetaKeywordsEn", 
    "Slug", "ThumbnailFile", "AuthorId", 
    "CreatedAt", "UpdatedAt", "DeletedAt", "IsDeleted", "IsActive", 
    "CreatedBy", "UpdatedBy", "DeletedBy"
) VALUES 
(
    1, 
    'راهنمای انتخاب عطر مناسب برای فصل تابستان', 
    'در این مقاله به شما کمک می‌کنیم تا عطری خنک و ماندگار برای روزهای گرم تابستان انتخاب کنید.', 
    'تابستان فصل گرما و تعریق است، بنابراین بهتر است از عطرهایی با نت‌های مرکباتی، آبی و گیاهی استفاده کنید. عطرهایی با غلظت ادوتویلت گزینه مناسبی هستند زیرا سنگین نیستند و در گرما آزاردهنده نمی‌باشند. برندهایی مثل دیور، شنل و کلایو کریستین انتخاب‌های خوبی برای این فصل هستند...', 
    'پیشنهاد نهایی ما برای تابستان، عطرهای خنک با نت‌های لیمو، نعناع و خیار است که هم طراوت‌بخش هستند و هم ماندگاری مناسبی در گرما دارند.', 
    'انتخاب عطر تابستانی با نت‌های مرکباتی و آبی', 
    'Guide to choosing the right perfume for summer', 
    'In this article, we help you choose a cool and long-lasting fragrance for hot summer days.', 
    'Summer is the season of heat and sweat, so it is better to use fragrances with citrus, aquatic and green notes. Eau de Toilette concentrations are suitable because they are not heavy and do not bother in the heat. Brands like Dior, Chanel and Clive Christian are good choices for this season...', 
    'Our final recommendation for summer is cool fragrances with notes of lemon, mint and cucumber that are both refreshing and have good longevity in the heat.', 
    'Choosing a summer fragrance with citrus and aquatic notes', 
    'راهنمای کامل انتخاب عطر مناسب برای فصل تابستان با نکات تخصصی', 
    'Complete guide to choosing the right perfume for summer with expert tips', 
    'عطر تابستانی, نت مرکباتی, عطر خنک, راهنمای عطر', 
    'summer fragrance, citrus notes, cool perfume, fragrance guide', 
    'guide-to-choosing-summer-perfume', 
    'summer-perfume-guide.jpg', 
    1, 
    '2026-01-10 10:30:00', '2026-01-10 10:30:00', NULL, false, true, 1, 1, NULL
),
(
    2, 
    'معرفی ۵ عطر لوکس و گران‌قیمت جهان', 
    'در این مطلب با گران‌ترین و لوکس‌ترین عطرهای دنیا آشنا می‌شوید که نمادی از تجمل و اصالت هستند.', 
    'عطرهای لوکس فقط یک رایحه نیستند، بلکه یک اثر هنری هستند. برندهایی مثل کلایو کریستین، روج دوفر و هنری ژاک با استفاده از نایاب‌ترین مواد اولیه مانند عنبر، عود و گل یاسمن هندی، عطرهایی می‌سازند که قیمت بعضی از آنها به چند ده هزار دلار می‌رسد. در این مقاله ۵ مورد از بهترین‌های آنها را بررسی می‌کنیم...', 
    'اگر به دنبال سرمایه‌گذاری روی یک عطر خاص هستید، کلایو کریستین شماره ۱ و عطر شالیمار از گران‌ترین و ماندگارترین گزینه‌ها هستند.', 
    'معرفی ۵ عطر لوکس و گران‌قیمت دنیا', 
    'Introduction to the 5 most luxurious and expensive perfumes in the world', 
    'In this article, you will get to know the most expensive and luxurious perfumes in the world, which are symbols of luxury and authenticity.', 
    'Luxury perfumes are not just a scent, but a work of art. Brands like Clive Christian, Roja Dove and Henry Jacques use the rarest raw materials such as ambergris, agarwood and Indian jasmine to create fragrances, some of which cost tens of thousands of dollars. In this article, we review 5 of the best...', 
    'If you are looking to invest in a special fragrance, Clive Christian No. 1 and Shalimar are among the most expensive and long-lasting options.', 
    'Introducing the 5 most luxurious and expensive perfumes in the world', 
    'معرفی ۵ عطر لوکس و فوق‌گران‌قیمت با برندهای معروف', 
    'Introduction to 5 ultra-luxury and expensive perfumes with famous brands', 
    'عطر لوکس, عطر گران‌قیمت, کلایو کریستین, عطر شالیمار', 
    'luxury perfume, expensive fragrance, Clive Christian, Shalimar perfume', 
    'top-5-luxury-perfumes', 
    'luxury-perfumes.jpg', 
    1, 
    '2026-01-12 14:20:00', '2026-01-12 14:20:00', NULL, false, true, 1, 1, NULL
),
(
    3, 
    'تفاوت ادکلن، ادوپرفیوم و ادوتویلت چیست؟', 
    'آیا می‌دانید تفاوت بین ادکلن، ادوپرفیوم و ادوتویلت چیست؟ در این مقاله کاملاً توضیح داده شده است.', 
    'بسیاری از افراد هنگام خرید عطر، با اصطلاحات Eau de Cologne، Eau de Toilette و Eau de Parfum مواجه می‌شوند و تفاوت آنها را نمی‌دانند. اصلی‌ترین تفاوت در غلظت روغن معطر است. ادکلن دارای ۲ تا ۵ درصد، ادوتویلت ۵ تا ۱۵ درصد و ادوپرفیوم ۱۵ تا ۲۰ درصد روغن معطر دارد. هرچه غلظت بیشتر باشد، ماندگاری و پخش بوی بیشتری خواهد داشت...', 
    'پس اگر به دنبال ماندگاری بالا هستید، سراغ ادوپرفیوم بروید و اگر رایحه‌ای ملایم و روزانه می‌خواهید، ادوتویلت انتخاب مناسبی است.', 
    'آشنایی با تفاوت‌های ادکلن، ادوتویلت و ادوپرفیوم', 
    'What is the difference between Eau de Cologne, Eau de Toilette and Eau de Parfum?', 
    'Do you know the difference between Eau de Cologne, Eau de Toilette and Eau de Parfum? This article explains it completely.', 
    'Many people face terms like Eau de Cologne, Eau de Toilette and Eau de Parfum when buying perfume and do not know their differences. The main difference is in the concentration of fragrance oil. Cologne has 2-5%, Eau de Toilette 5-15% and Eau de Parfum 15-20% fragrance oil. The higher the concentration, the more longevity and sillage...', 
    'So if you are looking for high longevity, go for Eau de Parfum, and if you want a mild daily scent, Eau de Toilette is a suitable choice.', 
    'Understanding the differences between Cologne, Toilette and Parfum', 
    'تفاوت ادکلن، ادوتویلت و ادوپرفیوم به زبان ساده', 
    'Difference between Eau de Cologne, Eau de Toilette and Eau de Parfum in simple language', 
    'ادکلن, ادوتویلت, ادوپرفیوم, غلظت عطر', 
    'Cologne, Eau de Toilette, Eau de Parfum, fragrance concentration', 
    'difference-between-cologne-toilette-parfum', 
    'fragrance-concentrations.jpg', 
    1, 
    '2026-01-15 09:00:00', '2026-01-15 09:00:00', NULL, false, true, 1, 1, NULL
),
(
    4, 
    'چگونه عطر را به درستی اسپری کنیم؟', 
    'روش صحیح اسپری کردن عطر تأثیر زیادی در ماندگاری و پخش بوی آن دارد. در این مقاله یاد بگیرید.', 
    'بسیاری از افراد عطر را روی مچ دست می‌مالند یا بعد از اسپری، آن را به هم می‌مالند که کاملاً اشتباه است. بهترین نقاط برای اسپری عطر، نقاط نبض‌دار مانند پشت گوش، مچ دست، آرنج و پشت زانو هستند. همچنین بهتر است عطر را از فاصله ۱۵ تا ۲۰ سانتی‌متری اسپری کنید و هرگز آن را به هم نمالید تا نت‌های اولیه تخریب نشوند...', 
    'با رعایت این نکات ساده، ماندگاری عطر خود را تا چند برابر افزایش دهید.', 
    'آموزش صحیح اسپری کردن عطر برای ماندگاری بیشتر', 
    'How to spray perfume correctly?', 
    'The correct way to spray perfume has a great impact on its longevity and sillage. Learn in this article.', 
    'Many people rub perfume on their wrists or rub it together after spraying, which is completely wrong. The best spots to spray perfume are pulse points such as behind the ears, wrists, elbows and behind the knees. Also, spray perfume from a distance of 15-20 cm and never rub it together to avoid destroying the top notes...', 
    'By following these simple tips, increase the longevity of your perfume several times.', 
    'Proper perfume spraying tutorial for more longevity', 
    'روش صحیح اسپری عطر برای ماندگاری بالا', 
    'Correct method of spraying perfume for high longevity', 
    'اسپری عطر, ماندگاری عطر, نقاط نبض‌دار', 
    'perfume spraying, fragrance longevity, pulse points', 
    'how-to-spray-perfume-correctly', 
    'perfume-spray-guide.jpg', 
    1, 
    '2026-01-18 16:45:00', '2026-01-18 16:45:00', NULL, false, true, 1, 1, NULL
),
(
    5, 
    'بهترین عطرهای زنانه ۲۰۲۶', 
    'در این مقاله بهترین عطرهای زنانه سال ۲۰۲۶ را به شما معرفی می‌کنیم که محبوبیت بالایی در سراسر جهان دارند.', 
    'سال ۲۰۲۶ سال عطرهای گلی-میوه‌ای و چوبی-دودی است. برندهایی مانند گوچی، ایو سن لوران و دیور جدیدترین ساخته‌های خود را با نت‌های گل یاسمن، گل رز ترکی، وانیل و چوب صندل روانه بازار کرده‌اند. در این مقاله ۱۰ عطر برتر زنانه را بر اساس نظر کاربران و منتقدان معرفی می‌کنیم...', 
    'اگر به دنبال یک عطر خاص و ماندگار برای بانوان هستید، گوچی بلوم و دیور جادوری مطلق پیشنهادات ما هستند.', 
    'معرفی بهترین عطرهای زنانه سال ۲۰۲۶', 
    'Best women''s perfumes of 2026', 
    'In this article, we introduce the best women''s perfumes of 2026 that are highly popular worldwide.', 
    '2026 is the year of floral-fruity and woody-smoky fragrances. Brands like Gucci, Yves Saint Laurent and Dior have released their latest creations with notes of jasmine, Turkish rose, vanilla and sandalwood. In this article, we introduce the top 10 women''s perfumes based on user and critic reviews...', 
    'If you are looking for a special and long-lasting perfume for women, Gucci Bloom and Dior J''adore Absolu are our recommendations.', 
    'Introducing the best women''s perfumes of 2026', 
    'بهترین عطرهای زنانه ۲۰۲۶ با رتبه‌بندی و نقد', 
    'Best women''s perfumes of 2026 with ratings and reviews', 
    'عطر زنانه, بهترین عطر ۲۰۲۶, عطر گلی, عطر وانیلی', 
    'women''s perfume, best perfume 2026, floral fragrance, vanilla perfume', 
    'best-women-perfumes-2026', 
    'women-perfumes-2026.jpg', 
    1, 
    '2026-01-20 11:10:00', '2026-01-20 11:10:00', NULL, false, true, 1, 1, NULL
)