INSERT INTO public."Blogs"(
    "Id", "TitleFa", "IntroFa", "ContentFa", "ConclusionFa", "ExcerptFa", 
    "TitleEn", "IntroEn", "ContentEn", "ConclusionEn", "ExcerptEn", 
    "MetaDescriptionFa", "MetaDescriptionEn", "MetaKeywordsFa", "MetaKeywordsEn", 
    "Slug", "ThumbnailFile", "AuthorId", 
    "CreatedAt", "UpdatedAt", "DeletedAt", "IsDeleted", "IsActive", 
    "CreatedBy", "UpdatedBy", "DeletedBy"
) VALUES 
(
    1, 
    'راهنمای خرید آنلاین مطمئن', 
    'در این مقاله نکات کلیدی برای یک خرید اینترنتی امن و آگاهانه را مرور می‌کنیم.', 
    'قبل از پرداخت، مشخصات محصول، موجودی، هزینه ارسال و سیاست بازگشت را بررسی کنید. فروشگاه‌های معتبر معمولاً فاکتور رسمی، پشتیبانی پاسخگو و اطلاعات شفاف قیمت دارند. مقایسه چند گزینه و خواندن نظرات کاربران هم به تصمیم بهتر کمک می‌کند...', 
    'با رعایت این نکات ساده، ریسک خرید آنلاین را به شکل چشمگیری کاهش می‌دهید.', 
    'نکات کاربردی برای خرید آنلاین مطمئن', 
    'Guide to safe online shopping', 
    'In this article, we review key tips for a secure and informed online purchase.', 
    'Before paying, check product specs, stock, shipping cost and return policy. Trusted stores usually provide official invoices, responsive support and transparent pricing. Comparing options and reading reviews also helps you decide better...', 
    'By following these simple tips, you can significantly reduce online shopping risk.', 
    'Practical tips for safer online shopping', 
    'راهنمای کامل خرید آنلاین مطمئن با نکات کاربردی', 
    'Complete guide to safe online shopping with practical tips', 
    'خرید آنلاین, فروشگاه اینترنتی, خرید مطمئن', 
    'online shopping, ecommerce, safe purchase', 
    'safe-online-shopping-guide', 
    'safe-online-shopping.jpg', 
    1, 
    '2026-01-10 10:30:00', '2026-01-10 10:30:00', NULL, false, true, 1, 1, NULL
),
(
    2, 
    'چگونه کالای اصل را از تقلبی تشخیص دهیم؟', 
    'چند نشانه ساده به شما کمک می‌کند اصالت کالا را بهتر ارزیابی کنید.', 
    'بسته‌بندی استاندارد، بارکد معتبر، فاکتور رسمی و مشخصات دقیق روی محصول از مهم‌ترین نشانه‌های اصالت هستند. قیمت غیرمنطقی پایین و فروشنده بدون هویت شفاف معمولاً هشدار جدی است. در صورت امکان، گارانتی و خدمات پس از فروش را هم بررسی کنید...', 
    'اگر نشانه‌های اصالت کامل نبود، از خرید صرف‌نظر کنید یا با پشتیبانی فروشگاه مشورت بگیرید.', 
    'راهکارهای تشخیص کالای اصل از تقلبی', 
    'How to tell authentic products from fakes', 
    'A few simple signs help you better evaluate product authenticity.', 
    'Standard packaging, valid barcodes, official invoices and accurate product specs are key authenticity signals. Unrealistically low prices and sellers without clear identity are serious red flags. Whenever possible, check warranty and after-sales service too...', 
    'If authenticity signals are incomplete, skip the purchase or consult store support.', 
    'Ways to distinguish authentic products from fakes', 
    'راهنمای تشخیص کالای اصل از تقلبی', 
    'Guide to distinguishing authentic products from fakes', 
    'کالای اصل, تشخیص تقلبی, خرید امن', 
    'authentic product, fake detection, safe buying', 
    'original-vs-fake-products', 
    'authentic-products.jpg', 
    1, 
    '2026-01-12 14:20:00', '2026-01-12 14:20:00', NULL, false, true, 1, 1, NULL
),
(
    3, 
    'نقش مشخصات فنی در انتخاب محصول', 
    'مشخصات فنی (Specifications) به شما کمک می‌کند محصول مناسب نیاز واقعی‌تان را انتخاب کنید.', 
    'در یک فروشگاه عمومی، هر دسته محصول مشخصات متفاوتی دارد؛ مثل ابعاد، جنس، وزن، توان مصرفی یا نوع بسته‌بندی. به جای تکیه فقط روی عنوان محصول، جدول مشخصات و توضیحات را با هم مقایسه کنید. این کار مخصوصاً وقتی چند برند مشابه دارید بسیار مفید است...', 
    'قبل از افزودن به سبد، مشخصات کلیدی را با نیاز خود مطابقت دهید.', 
    'اهمیت مشخصات فنی در خرید آنلاین', 
    'Why product specifications matter', 
    'Specifications help you choose the product that truly matches your needs.', 
    'In a general storefront, each category has different specs such as dimensions, material, weight, power or packaging type. Instead of relying only on the title, compare the specs table with the description. This is especially useful when several similar brands are available...', 
    'Before adding to cart, match key specs with your actual needs.', 
    'The importance of technical specs in online shopping', 
    'نقش مشخصات فنی در انتخاب درست محصول', 
    'The role of specifications in choosing the right product', 
    'مشخصات فنی, انتخاب محصول, خرید اینترنتی', 
    'product specs, product selection, ecommerce', 
    'why-product-specifications-matter', 
    'product-specifications.jpg', 
    1, 
    '2026-01-15 09:00:00', '2026-01-15 09:00:00', NULL, false, true, 1, 1, NULL
),
(
    4, 
    'نکات بسته‌بندی و ارسال امن', 
    'بسته‌بندی مناسب نقش مهمی در سالم رسیدن کالا دارد.', 
    'فروشگاه‌های حرفه‌ای معمولاً از ضربه‌گیر، کارتن مقاوم و لیبل‌گذاری دقیق استفاده می‌کنند. هنگام تحویل، سلامت بسته‌بندی را بررسی کنید و در صورت آسیب‌دیدگی، همان لحظه به پشتیبانی اطلاع دهید. ثبت تصویر از بسته هنگام دریافت هم می‌تواند مفید باشد...', 
    'با بررسی بسته در لحظه تحویل، احتمال اختلاف بعد از خرید را کاهش می‌دهید.', 
    'راهنمای بسته‌بندی و دریافت امن سفارش', 
    'Secure packaging and delivery tips', 
    'Proper packaging plays a major role in receiving undamaged products.', 
    'Professional stores usually use cushioning, sturdy cartons and clear labeling. On delivery, check packaging condition and report damage to support immediately. Taking a photo of the package on receipt can also help...', 
    'Inspecting the package on delivery reduces post-purchase disputes.', 
    'Guide to secure packaging and order receipt', 
    'نکات بسته‌بندی و ارسال امن سفارش', 
    'Tips for secure packaging and delivery', 
    'بسته‌بندی, ارسال امن, تحویل سفارش', 
    'packaging, secure shipping, order delivery', 
    'secure-packaging-and-delivery', 
    'secure-packaging.jpg', 
    1, 
    '2026-01-18 16:45:00', '2026-01-18 16:45:00', NULL, false, true, 1, 1, NULL
),
(
    5, 
    'چطور برای مناسبت‌ها هدیه مناسب انتخاب کنیم؟', 
    'انتخاب هدیه فقط به سلیقه شخصی محدود نیست؛ کاربرد و بسته‌بندی هم مهم است.', 
    'برای هدیه، ابتدا بودجه، سلیقه گیرنده و فضای استفاده را مشخص کنید. محصولات دکوری، ظروف پذیرایی و ست‌های کاربردی معمولاً گزینه‌های امنی هستند. اگر تردید دارید، سراغ اقلامی بروید که هم زیبایی دارند و هم استفاده روزمره...', 
    'یک هدیه خوب، هم کاربردی است و هم تجربه باز کردن بسته‌ای خوشایند می‌سازد.', 
    'راهنمای انتخاب هدیه مناسب برای مناسبت‌ها', 
    'How to choose the right gift for occasions', 
    'Choosing a gift is not only about personal taste; usefulness and packaging matter too.', 
    'For gifts, first define budget, recipient taste and intended use. Decor items, serving ware and practical sets are usually safe options. If unsure, choose items that are both beautiful and useful day to day...', 
    'A good gift is useful and creates a pleasant unboxing experience.', 
    'Guide to choosing the right gift for occasions', 
    'راهنمای انتخاب هدیه مناسب', 
    'Guide to choosing suitable gifts', 
    'هدیه, مناسبت, انتخاب هدیه', 
    'gift, occasion, gift selection', 
    'choose-right-gift', 
    'gift-guide.jpg', 
    1, 
    '2026-01-20 11:10:00', '2026-01-20 11:10:00', NULL, false, true, 1, 1, NULL
);
