FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY . .

RUN dotnet restore Api/Api.csproj

ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 8080

CMD ["dotnet","watch","run","--project","Api/Api.csproj","--urls=http://0.0.0.0:8080"]